# default_language_version:
#   python: python3.10
repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
    


  # Linter: Flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]        

  # Import sorter: isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (Python import sorter)
        files: \.py$

  # Docstring style checker: pydocstyle
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [--convention=google]
        additional_dependencies: []
        language_version: python3.10
        require_serial: true
        # disable build isolation
        install_command: python -m pip install --no-build-isolation {packages}
