name: Phase 1 CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black pytest

      - name: Lint with flake8
        run: flake8 src tests

      - name: Check formatting with black
        run: black --check src tests

      - name: Run unit tests with PYTHONPATH set
        run: |
          PYTHONPATH=src pytest tests
          
      - name: Debug Python env
        run: |
          python --version
          pip list
          echo $PYTHONPATH

          
      - name: Debug test discovery
        run: |
          echo "PYTHONPATH=$PYTHONPATH"
          pytest --collect-only

